name: garmin_activity_reports
description: Garmin Activity Reports

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  health: ^13.2.1

flutter:
  uses-material-design: true